from . import shift_swap_mixin
from . import res_partner
from . import shift_swap
from . import exchange_request
from . import exchange
from . import planning
from . import dated_template
from . import res_company
from . import res_config_settings
from . import solidarity_shift_offer
from . import solidarity_shift_request
from . import task
