# SPDX-FileCopyrightText: 2025 Coop IT Easy SC
#
# SPDX-License-Identifier: AGPL-3.0-or-later

from . import test_volunteer_common
from . import test_volunteer_generator_subscription_common

from . import test_volunteer_shift
from . import test_volunteer_shift_participation
from . import test_volunteer_shift_recurrent_generator_generation
from . import test_volunteer_shift_recurrent_generator_cancellation
from . import test_volunteer_shift_recurrent_generator_dates_constraints
from . import test_volunteer_shift_recurrent_generator_state_change_permissions
from . import test_volunteer_shift_recurrent_generator_write_permissions
from . import test_volunteer_shift_recurrent_subscription
from . import test_volunteer_shift_recurrent_subscription_cancellation
from . import test_volunteer_shift_recurrent_subscription_dates_constraints
from . import test_volunteer_shift_recurrent_subscription_participation
from . import test_volunteer_shift_recurrent_subscription_write_permissions
