# Do NOT update manually; changes here will be overwritten by Copier
_commit: v2.1.8
_src_path: https://github.com/coopiteasy/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 16.0
org_name: Coop IT Easy SC
org_slug: beescoop
rebel_module_groups: []
repo_description: null
repo_name: Obeesdoo
repo_slug: Obeesdoo
repo_website: https://github.com/beescoop/Obeesdoo
travis_apt_packages: []
travis_apt_sources: []

