{
    "name": "stock_move_view_order",
    "author": "Coop IT Easy SC, Polln group",
    "summary": "Reverse the order stock move order by from newest to oldest." "",
    "website": "https://github.com/beescoop/Obeesdoo",
    "licence": "AGPL-3",
    "category": "Extra tools",
    "version": "12.0.2.1.0",
    "license": "AGPL-3",
    "depends": ["base", "stock"],
    "data": ["views/stock_move_line_views.xml"],
    "installable": True,
    "application": False,
    "auto_install": False,
}
