{
    "name": "Beescoop link with easy my coop",
    "summary": """Link between beesdoo customization and easy_my_coop""",
    "author": "BEES coop, Coop IT Easy SCRLfs",
    "website": "https://github.com/beescoop/Obeesdoo",
    "category": "Cooperative management",
    "version": "12.0.1.0.1",
    "depends": [
        "beesdoo_base",
        "beesdoo_shift",
        "easy_my_coop",
        "easy_my_coop_website",
        "partner_age",
    ],
    "data": [
        "views/res_company.xml",
        'views/res_partner.xml',
        "views/subscription_request.xml",
        "views/subscription_templates.xml",
        "views/product.xml",
    ],
    "demo": ["demo/product_share.xml"],
    "auto_install": True,
    "license": "AGPL-3",
}
